[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "nginx"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "cp /app/nginx.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

[static]
extended = true
