[phases.setup]
nixPkgs = ["nodejs_20", "nginx"]

[phases.build]
cmds = ["npm install", "npm run build"]

[start]
cmd = "cp /app/nginx.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

[static]
extended = true
